apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockscore-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/blockscore-pod-execution-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: blockscore-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blockscore-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: blockscore-service-account
    namespace: default
roleRef:
  kind: Role
  name: blockscore-role
  apiGroup: rbac.authorization.k8s.io
